//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIN.BuysServices
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://siat.impuestos.gob.bo/", ConfigurationName="SIN.BuysServices.ServicioFacturacion")]
    internal interface ServicioFacturacion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.BuysServices.verificarComunicacionResponse> verificarComunicacionAsync(SIN.BuysServices.verificarComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.BuysServices.validacionRecepcionPaqueteComprasResponse> validacionRecepcionPaqueteComprasAsync(SIN.BuysServices.validacionRecepcionPaqueteCompras request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.BuysServices.recepcionPaqueteComprasResponse> recepcionPaqueteComprasAsync(SIN.BuysServices.recepcionPaqueteCompras request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.BuysServices.anulacionCompraResponse> anulacionCompraAsync(SIN.BuysServices.anulacionCompra request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.BuysServices.confirmacionComprasResponse> confirmacionComprasAsync(SIN.BuysServices.confirmacionCompras request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<SIN.BuysServices.consultaComprasResponse> consultaComprasAsync(SIN.BuysServices.consultaCompras request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaComunicacion : modelDto
    {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeServicio : modelDto
    {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified
        {
            get
            {
                return this.codigoFieldSpecified;
            }
            set
            {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaConsultaCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudConsultaCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacionCompra))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcionCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class modelDto : model
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modelDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaConsultaCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudConsultaCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacionCompra))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcionCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class model
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaConsultaCompras : modelDto
    {
        
        private byte[] archivoField;
        
        private mensajeRecepcion[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] archivo
        {
            get
            {
                return this.archivoField;
            }
            set
            {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public mensajeRecepcion[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeRecepcion : mensajeServicio
    {
        
        private bool advertenciaField;
        
        private bool advertenciaFieldSpecified;
        
        private int numeroArchivoField;
        
        private bool numeroArchivoFieldSpecified;
        
        private int numeroDetalleField;
        
        private bool numeroDetalleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool advertencia
        {
            get
            {
                return this.advertenciaField;
            }
            set
            {
                this.advertenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool advertenciaSpecified
        {
            get
            {
                return this.advertenciaFieldSpecified;
            }
            set
            {
                this.advertenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroArchivo
        {
            get
            {
                return this.numeroArchivoField;
            }
            set
            {
                this.numeroArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroArchivoSpecified
        {
            get
            {
                return this.numeroArchivoFieldSpecified;
            }
            set
            {
                this.numeroArchivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroDetalle
        {
            get
            {
                return this.numeroDetalleField;
            }
            set
            {
                this.numeroDetalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroDetalleSpecified
        {
            get
            {
                return this.numeroDetalleFieldSpecified;
            }
            set
            {
                this.numeroDetalleFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaRecepcion : modelDto
    {
        
        private string codigoDescripcionField;
        
        private int codigoEstadoField;
        
        private bool codigoEstadoFieldSpecified;
        
        private string codigoRecepcionField;
        
        private mensajeRecepcion[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoDescripcion
        {
            get
            {
                return this.codigoDescripcionField;
            }
            set
            {
                this.codigoDescripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoEstado
        {
            get
            {
                return this.codigoEstadoField;
            }
            set
            {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoEstadoSpecified
        {
            get
            {
                return this.codigoEstadoFieldSpecified;
            }
            set
            {
                this.codigoEstadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoRecepcion
        {
            get
            {
                return this.codigoRecepcionField;
            }
            set
            {
                this.codigoRecepcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public mensajeRecepcion[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudConsultaCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacionCompra))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcionCompras))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCompras : modelDto
    {
        
        private int codigoAmbienteField;
        
        private int codigoPuntoVentaField;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cufdField;
        
        private string cuisField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cufd
        {
            get
            {
                return this.cufdField;
            }
            set
            {
                this.cufdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudConsultaCompras : solicitudCompras
    {
        
        private System.DateTime fechaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudAnulacionCompra : solicitudCompras
    {
        
        private string codAutorizacionField;
        
        private long nitProveedorField;
        
        private string nroDuiDimField;
        
        private long nroFacturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codAutorizacion
        {
            get
            {
                return this.codAutorizacionField;
            }
            set
            {
                this.codAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long nitProveedor
        {
            get
            {
                return this.nitProveedorField;
            }
            set
            {
                this.nitProveedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nroDuiDim
        {
            get
            {
                return this.nroDuiDimField;
            }
            set
            {
                this.nroDuiDimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long nroFactura
        {
            get
            {
                return this.nroFacturaField;
            }
            set
            {
                this.nroFacturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionCompras : solicitudCompras
    {
        
        private byte[] archivoField;
        
        private int cantidadFacturasField;
        
        private System.DateTime fechaEnvioField;
        
        private int gestionField;
        
        private string hashArchivoField;
        
        private int periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] archivo
        {
            get
            {
                return this.archivoField;
            }
            set
            {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadFacturas
        {
            get
            {
                return this.cantidadFacturasField;
            }
            set
            {
                this.cantidadFacturasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaEnvio
        {
            get
            {
                return this.fechaEnvioField;
            }
            set
            {
                this.fechaEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int gestion
        {
            get
            {
                return this.gestionField;
            }
            set
            {
                this.gestionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string hashArchivo
        {
            get
            {
                return this.hashArchivoField;
            }
            set
            {
                this.hashArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudValidacionRecepcionCompras : solicitudCompras
    {
        
        private string codigoRecepcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoRecepcion
        {
            get
            {
                return this.codigoRecepcionField;
            }
            set
            {
                this.codigoRecepcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class verificarComunicacion
    {
        
        public verificarComunicacion()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class verificarComunicacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.BuysServices.respuestaComunicacion @return;
        
        public verificarComunicacionResponse()
        {
        }
        
        public verificarComunicacionResponse(SIN.BuysServices.respuestaComunicacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteCompras", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class validacionRecepcionPaqueteCompras
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.BuysServices.solicitudValidacionRecepcionCompras SolicitudValidacionRecepcionCompras;
        
        public validacionRecepcionPaqueteCompras()
        {
        }
        
        public validacionRecepcionPaqueteCompras(SIN.BuysServices.solicitudValidacionRecepcionCompras SolicitudValidacionRecepcionCompras)
        {
            this.SolicitudValidacionRecepcionCompras = SolicitudValidacionRecepcionCompras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteComprasResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class validacionRecepcionPaqueteComprasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.BuysServices.respuestaRecepcion RespuestaServicioFacturacion;
        
        public validacionRecepcionPaqueteComprasResponse()
        {
        }
        
        public validacionRecepcionPaqueteComprasResponse(SIN.BuysServices.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteCompras", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class recepcionPaqueteCompras
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.BuysServices.solicitudRecepcionCompras SolicitudRecepcionCompras;
        
        public recepcionPaqueteCompras()
        {
        }
        
        public recepcionPaqueteCompras(SIN.BuysServices.solicitudRecepcionCompras SolicitudRecepcionCompras)
        {
            this.SolicitudRecepcionCompras = SolicitudRecepcionCompras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteComprasResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class recepcionPaqueteComprasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.BuysServices.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionPaqueteComprasResponse()
        {
        }
        
        public recepcionPaqueteComprasResponse(SIN.BuysServices.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionCompra", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class anulacionCompra
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.BuysServices.solicitudAnulacionCompra SolicitudAnulacionCompra;
        
        public anulacionCompra()
        {
        }
        
        public anulacionCompra(SIN.BuysServices.solicitudAnulacionCompra SolicitudAnulacionCompra)
        {
            this.SolicitudAnulacionCompra = SolicitudAnulacionCompra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionCompraResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class anulacionCompraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.BuysServices.respuestaRecepcion RespuestaServicioFacturacion;
        
        public anulacionCompraResponse()
        {
        }
        
        public anulacionCompraResponse(SIN.BuysServices.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmacionCompras", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class confirmacionCompras
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.BuysServices.solicitudRecepcionCompras SolicitudConfirmacionCompras;
        
        public confirmacionCompras()
        {
        }
        
        public confirmacionCompras(SIN.BuysServices.solicitudRecepcionCompras SolicitudConfirmacionCompras)
        {
            this.SolicitudConfirmacionCompras = SolicitudConfirmacionCompras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmacionComprasResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class confirmacionComprasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.BuysServices.respuestaRecepcion RespuestaServicioFacturacion;
        
        public confirmacionComprasResponse()
        {
        }
        
        public confirmacionComprasResponse(SIN.BuysServices.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaCompras", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class consultaCompras
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.BuysServices.solicitudConsultaCompras SolicitudConsultaCompras;
        
        public consultaCompras()
        {
        }
        
        public consultaCompras(SIN.BuysServices.solicitudConsultaCompras SolicitudConsultaCompras)
        {
            this.SolicitudConsultaCompras = SolicitudConsultaCompras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaComprasResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    internal partial class consultaComprasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SIN.BuysServices.respuestaConsultaCompras RespuestaServicioFacturacion;
        
        public consultaComprasResponse()
        {
        }
        
        public consultaComprasResponse(SIN.BuysServices.respuestaConsultaCompras RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    internal interface ServicioFacturacionChannel : SIN.BuysServices.ServicioFacturacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    internal partial class ServicioFacturacionClient : System.ServiceModel.ClientBase<SIN.BuysServices.ServicioFacturacion>, SIN.BuysServices.ServicioFacturacion
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioFacturacionClient() : 
                base(ServicioFacturacionClient.GetDefaultBinding(), ServicioFacturacionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioFacturacionPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioFacturacionClient.GetBindingForEndpoint(endpointConfiguration), ServicioFacturacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioFacturacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioFacturacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SIN.BuysServices.verificarComunicacionResponse> verificarComunicacionAsync(SIN.BuysServices.verificarComunicacion request)
        {
            return base.Channel.verificarComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.BuysServices.validacionRecepcionPaqueteComprasResponse> validacionRecepcionPaqueteComprasAsync(SIN.BuysServices.validacionRecepcionPaqueteCompras request)
        {
            return base.Channel.validacionRecepcionPaqueteComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.BuysServices.recepcionPaqueteComprasResponse> recepcionPaqueteComprasAsync(SIN.BuysServices.recepcionPaqueteCompras request)
        {
            return base.Channel.recepcionPaqueteComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.BuysServices.anulacionCompraResponse> anulacionCompraAsync(SIN.BuysServices.anulacionCompra request)
        {
            return base.Channel.anulacionCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.BuysServices.confirmacionComprasResponse> confirmacionComprasAsync(SIN.BuysServices.confirmacionCompras request)
        {
            return base.Channel.confirmacionComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIN.BuysServices.consultaComprasResponse> consultaComprasAsync(SIN.BuysServices.consultaCompras request)
        {
            return base.Channel.consultaComprasAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioFacturacionPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioFacturacionPort))
            {
                return new System.ServiceModel.EndpointAddress("https://pilotosiatservicios.impuestos.gob.bo/v2/ServicioRecepcionCompras");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioFacturacionClient.GetBindingForEndpoint(EndpointConfiguration.ServicioFacturacionPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioFacturacionClient.GetEndpointAddress(EndpointConfiguration.ServicioFacturacionPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioFacturacionPort,
        }
    }
}
